load("//bazel:base_cc.bzl", "base_cc_library")

base_cc_library(
    name = "eintr_wrapper",
    hdrs = ["eintr_wrapper.h"],
    visibility = ["//visibility:public"],
    deps = ["//base:build_config"],
)
