load("//bazel:base_cc.bzl", "base_cc_library")

base_cc_library(
    name = "safe_conversions",
    hdrs = [
        "safe_conversions.h",
        "safe_conversions_arm_impl.h",
        "safe_conversions_impl.h",
    ],
    visibility = ["//visibility:public"],
    deps = ["//base:build_config"],
)
