load("//bazel:base_cc.bzl", "base_cc_library")

base_cc_library(
    name = "stack_container",
    hdrs = ["stack_container.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//base:build_config",
    ],
)
