cc_library(
    name = "export",
    hdrs = [
        "export.h",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "no_destructor",
    hdrs = ["no_destructor.h"],
    visibility = ["//visibility:public"],
)
